name: check_mate
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+456

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  appinio_swiper: ^2.0.3
  cached_network_image: ^3.2.1
  cupertino_icons: ^1.0.2
  firebase_core: ^2.20.0
  firebase_messaging: ^14.7.2
  flutter:
    sdk: flutter
  flutter_image_compress: ^2.1.0
  flutter_local_notifications: ^16.1.0
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.8
  flutter_swipecards: ^0.2.1
  fluttertoast: ^8.0.9
  geocoding: ^2.0.4
  geolocator: ^10.1.0
  google_mobile_ads: ^3.1.0
  google_places_flutter: ^2.0.5
<<<<<<< HEAD
  google_sign_in: ^5.4.0
  http: ^0.13.4
  image_picker: ^0.8.5+3
  in_app_update: ^3.0.0
  intl: ^0.17.0
  logger: ^1.1.0
  new_version: ^0.3.1
  preload_page_view: ^0.1.6
=======
  flutter_chat_ui :
  google_sign_in: ^6.1.5
  http: ^1.1.0
  image_picker: ^1.0.4
  intl: ^0.18.1
  logger: ^2.0.2+1
  preload_page_view: ^0.2.0
>>>>>>> 62b38beeda1f0d7d623ad8a7c641554bf0c87ed8
  restart_app: ^1.1.0+1
  shared_preferences: ^2.0.15

  velocity_x: ^4.1.1
  # workmanager: ^0.5.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
  fonts:
    - family: Ribeye
      fonts:
        - asset: assets/fonts/ribeyeregular400.ttf
          weight: 400
    - family: Roboto
      fonts:
        - asset: assets/fonts/robotoregular400.ttf
          weight: 400
        - asset: assets/fonts/robotomedium500.ttf
          weight: 500
        - asset: assets/fonts/robotolight300.ttf
          weight: 300
        - asset: assets/fonts/robotorobotoromanmedium500.ttf
          weight: 500
        - asset: assets/fonts/robotorobotoromanregular400.ttf
          weight: 400
        - asset: assets/fonts/robotorobotoromanbold700.ttf
          weight: 700
    - family: Lato
      fonts:
        - asset: assets/fonts/latoregular400.ttf
          weight: 400
    - family: Playfair Display
      fonts:
        - asset: assets/fonts/playfairdisplayplayfairdisplayromanbold700.ttf
          weight: 700
    - family: Inter
      fonts:
        - asset: assets/fonts/intermedium500.ttf
          weight: 500
        - asset: assets/fonts/interbold700.ttf
          weight: 700
    - family: Ledger
      fonts:
        - asset: assets/fonts/ledgerregular400.ttf
          weight: 400
    - family: Ribeye Marrow
      fonts:
        - asset: assets/fonts/ribeyemarrowregular400.ttf
          weight: 400
