// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLfuyDvfB0tGLeXpEbUIn2A0T4o9KiWU4',
    appId: '1:313901529256:android:ca8a36cea4ea5daa2dea9d',
    messagingSenderId: '313901529256',
    projectId: 'relation-355921',
    storageBucket: 'relation-355921.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACHTOBPpCSPHPrW1nxS1Re9dChd7-SAOk',
    appId: '1:313901529256:ios:5ef7cf37b8207d782dea9d',
    messagingSenderId: '313901529256',
    projectId: 'relation-355921',
    storageBucket: 'relation-355921.appspot.com',
    androidClientId: '313901529256-kh8rnl1hkv94h4gfsvats3lfgedarrh8.apps.googleusercontent.com',
    iosClientId: '313901529256-aos7vse3abutnr4fgq4asn4rfpi62q94.apps.googleusercontent.com',
    iosBundleId: 'com.example.checkMate',
  );
}
